%global gitcommit a014f13c09996116360be16224f568372cc33289
%global gitshort  %(echo %{gitcommit} | cut -c 1-8)
%global gitdate   20241115

# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           dnst
Version:        0.1.0~%{gitdate}git%{gitshort}
Release:        %autorelease
Summary:        Rust reimplementation of important ldns programs

SourceLicense:  BSD-3-Clause
# Apache-2.0 OR MIT
# BSD-2-Clause OR Apache-2.0 OR MIT
# BSD-3-Clause
# ISC
# ISC AND MIT AND OpenSSL
# MIT
# MIT OR Apache-2.0
# Unlicense OR MIT
License: (Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND BSD-3-Clause AND ISC AND MIT AND OpenSSL AND MIT AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/nlnetlabs/dnst/
Source:         %{url}/archive/%{gitcommit}/%{name}-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Rust reimplementation of important ldns programs.}

%description %{_description}

%prep
%autosetup -n dnst-%{gitcommit} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
date +TODAY=%04Y%02m%02d
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/dnst
%{_bindir}/ldns

%changelog
%autochangelog
