# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

Name:           dnst
Version:        0.1.0
Release:        %autorelease
Summary:        Rust reimplementation of important ldns programs

SourceLicense:  BSD-3-Clause
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/nlnetlabs/dnst/
Source:         # FIXME

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Rust reimplementation of important ldns programs.}

%description %{_description}

%prep
%autosetup -n dnst-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/dnst
%{_bindir}/ldns

%changelog
%autochangelog
